# Production Environment Inventory
# PLACEHOLDER IPs - replace with actual production device management addresses
# before use. Production credentials are managed via Ansible Vault.
# See docs/credential-management.md for vault setup instructions.
all:
  children:
    routers:
      hosts:
        R1:
          ansible_host: 10.0.1.1   # PLACEHOLDER: production R1 management IP
        R2:
          ansible_host: 10.0.1.2   # PLACEHOLDER: production R2 management IP
        R3:
          ansible_host: 10.0.1.3   # PLACEHOLDER: production R3 management IP
