# CML Test Environment Inventory
# Management IPs are DHCP-assigned via bridge10 (192.168.10.0/24)
# Update ansible_host values after CML lab start using:
#   show ip interface brief on each router's Gi0/0
# See inventory/cml-lab.yml for CML lab UUID and node metadata
all:
  children:
    routers:
      hosts:
        R1:
          ansible_host: 192.168.10.207  # CML DHCP via bridge10 (lab: bgp-demo)
        R2:
          ansible_host: 192.168.10.206  # CML DHCP via bridge10 (lab: bgp-demo)
        R3:
          ansible_host: 192.168.10.212  # CML DHCP via bridge10 (lab: bgp-demo)
